name: rame_lakat_app
description: Aplikacija za rame i lakat

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  url_launcher: ^6.1.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.16
  flutter_launcher_icons: ^0.9.2
  equatable: ^2.0.3
  flutter_datetime_picker: ^1.5.1
  flutter_rating_bar: ^4.0.0
  cloud_firestore: ^3.1.9
  firebase_auth: ^3.3.13
  firebase_core: ^1.12.0
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  get_storage: ^2.0.3
  flutter_html: ^2.2.1
  flutter_native_splash: ^2.1.6

flutter_icons:
  image_path: "images/app_logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
flutter:
  assets:
    - images/
    - localization/
  fonts:
    - family: ChakraPetch
      fonts:
        - asset: fonts/ChakraPetch-Regular.ttf
        - asset: fonts/ChakraPetch-Italic.ttf
  uses-material-design: true

flutter_native_splash:
  color: "#ECF1F9"
  image: images/logo.png
  color_dark: "#ECF1F9"
  image_dark: images/logo.png
  android_12:
  fullscreen: true