name: rame_lakat_app
description: Aplikacija za rame i lakat

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  flutter_rating_bar: ^4.0.0
  cloud_firestore: ^3.1.9
  firebase_auth: ^3.3.13
  firebase_core: ^1.12.0
  shared_preferences: ^2.0.13
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  freezed: ^1.1.0
  flutter_lints: ^1.0.0
flutter:
  assets:
    - images/
    - localization/
  fonts:
    - family: ChakraPetch
      fonts:
        - asset: fonts/ChakraPetch-Regular.ttf
        - asset: fonts/ChakraPetch-Italic.ttf
  uses-material-design: true
